#!/bin/sh

# Reinitialize Touch Pad to fix non-working Track Point

case $1 in
    post)
	sleep 1
	echo -n none > /sys/devices/platform/i8042/serio1/drvctl
	sleep 1
	echo -n reconnect > /sys/devices/platform/i8042/serio1/drvctl
	synclient TapButton1=1 TapButton2=2 TapButton3=3
;;
esac
