#!/bin/sh

# Reinitialize Touch Pad to fix non-working Track Point

case $1 in
    post)
	echo -n none > /sys/devices/platform/i8042/serio1/drvctl
	echo -n reconnect > /sys/devices/platform/i8042/serio1/drvctl
;;
esac
